# Generated by Django 4.1.1 on 2022-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('data', models.JSONField(primary_key=True, serialize=False)),
            ],
        ),
    ]
