# Generated by Django 4.1.1 on 2022-09-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinput', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='data',
            new_name='input_data',
        ),
    ]
